Implement publish_override_ok as a toggle to existing context var
hysds/hysds pull request #166
Opened 2023-05-22 22:48 UTC by joshgarde

Part of HC-473 work

2024-03-14 21:55 UTC, pymonger approved these changes
LGTM. @mcayanan?

2024-03-14 21:58 UTC, DustinKLo submitted a review, later dismissed

2024-03-14 22:03 UTC, mcayanan requested changes
Do we need a version bump to 1.3.2?

https://github.com/hysds/hysds/blob/944d3a89997b1aff416dc627b095a6b5e10b2242/hysds/__init__.py#L6

2024-03-14 22:49 UTC, pymonger commented
> Do we need a version bump to 1.3.2?
> 
> https://github.com/hysds/hysds/blob/944d3a89997b1aff416dc627b095a6b5e10b2242/hysds/__init__.py#L6

That's right. @joshgarde when you get a chance can you also bump the versions (patch number) of the repos that were updated?

2024-03-14 23:50 UTC, pymonger approved these changes

2024-03-15 00:08 UTC, pymonger approved these changes

2024-03-15 00:09 UTC, mcayanan approved these changes

2024-03-15 00:15 UTC, DustinKLo approved these changes

2024-03-15 00:59 UTC, merged